export const EMAIL_VERIFICATION_PROGRESS = 'EMAIL_VERIFICATION_PROGRESS';
export const EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS';
export const EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED';
export const PWD_VERIFICATION_PROGRESS = 'PWD_VERIFICATION_PROGRESS';
export const PWD_VERIFICATION_SUCCESS = 'PWD_VERIFICATION_SUCCESS';
export const PWD_VERIFICATION_FAILED = 'PWD_VERIFICATION_FAILED';